title: Projet de mémoire
description: >
  Dans le cadre du Merfa du CNAM.
baseurl: ""
url: ""
paginate:	2 # The number of posts to show per page on your homepage
name: "Stéphane Manet"
author_url: https://stephma.net
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate

github_url: stephmnt/memoire

bibtex:
  - bib/test1.bib
  - bib/test2.bib
