title: Mémoire de recherche
description: >
  Master Européen de Recherche en Formation des adultes
baseurl:
url:
paginate:	2 # The number of posts to show per page on your homepage
name: "Stéphane Manet"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate

github_url: stephmnt/memoire

bibtex:
  - bib/test1.bib
  - bib/test2.bib
